### ISSUE TITLE
ViewModels state

### ISSUE THREAD

**Issue by adin234** [esafirm/conductor-extra#5]
are there any examples on how to retain the view model on config change?

**Comment by esafirm** [comment]
Sorry, what do you mean by `ViewModels`? 

If you meant retaining value over config change then Conductor already handle this already. 
Because under the hood it use `Fragment.setRetainInstance(true)` 

Please look at this: https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/internal/LifecycleHandler.java#L52

For Conductor extra, it takes this further with saving between activity recreation
https://github.com/esafirm/conductor-extra/blob/master/conductor-extra-screen/src/main/java/nolambda/screen/StatefulScreen.kt#L29

Hope it helps!

**Comment by adin234** [comment]
@esafirm I am using android databinding and used two-way binding with my view and controller. I assumed that the inputs for my for would remain on configuration change but they didn't. this might be because of how i create my viewmodels so i asked if there are any examples for this

**Comment by adin234** [comment]
Im closing this, the problem is with my initialization of ViewModel, solved by injecting the viewmodel with Activity Scope
